// flow-typed signature: e83ee472d6e32372b8414d332fc15da6
// flow-typed version: <<STUB>>/eslint-plugin-underscore-to-lodash_v^0.0.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-underscore-to-lodash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-underscore-to-lodash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-underscore-to-lodash/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-underscore-to-lodash/lib/rules/prefer-import-lodash' {
  declare module.exports: any;
}

declare module 'eslint-plugin-underscore-to-lodash/tests/lib/rules/prefer-import-lodash' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-underscore-to-lodash/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-underscore-to-lodash/lib'>;
}
declare module 'eslint-plugin-underscore-to-lodash/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-underscore-to-lodash/lib'>;
}
declare module 'eslint-plugin-underscore-to-lodash/lib/rules/prefer-import-lodash.js' {
  declare module.exports: $Exports<'eslint-plugin-underscore-to-lodash/lib/rules/prefer-import-lodash'>;
}
declare module 'eslint-plugin-underscore-to-lodash/tests/lib/rules/prefer-import-lodash.js' {
  declare module.exports: $Exports<'eslint-plugin-underscore-to-lodash/tests/lib/rules/prefer-import-lodash'>;
}
