// flow-typed signature: aed0dded2805e7900e3d3f94487b97c5
// flow-typed version: <<STUB>>/eslint-plugin-only-var_v^0.1.2/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-only-var'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-only-var' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-only-var/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-only-var/index' {
  declare module.exports: $Exports<'eslint-plugin-only-var'>;
}
declare module 'eslint-plugin-only-var/index.js' {
  declare module.exports: $Exports<'eslint-plugin-only-var'>;
}
declare module 'eslint-plugin-only-var/test.js' {
  declare module.exports: $Exports<'eslint-plugin-only-var/test'>;
}
