// flow-typed signature: 8222eb74d122194674c02302a470bdfe
// flow-typed version: <<STUB>>/glob-all_v^3.1.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glob-all'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glob-all' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glob-all/example/async' {
  declare module.exports: any;
}

declare module 'glob-all/example/events' {
  declare module.exports: any;
}

declare module 'glob-all/example/order' {
  declare module.exports: any;
}

declare module 'glob-all/example/perf' {
  declare module.exports: any;
}

declare module 'glob-all/example/sync' {
  declare module.exports: any;
}

declare module 'glob-all/glob-all' {
  declare module.exports: any;
}

declare module 'glob-all/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glob-all/example/async.js' {
  declare module.exports: $Exports<'glob-all/example/async'>;
}
declare module 'glob-all/example/events.js' {
  declare module.exports: $Exports<'glob-all/example/events'>;
}
declare module 'glob-all/example/order.js' {
  declare module.exports: $Exports<'glob-all/example/order'>;
}
declare module 'glob-all/example/perf.js' {
  declare module.exports: $Exports<'glob-all/example/perf'>;
}
declare module 'glob-all/example/sync.js' {
  declare module.exports: $Exports<'glob-all/example/sync'>;
}
declare module 'glob-all/glob-all.js' {
  declare module.exports: $Exports<'glob-all/glob-all'>;
}
declare module 'glob-all/test/test.js' {
  declare module.exports: $Exports<'glob-all/test/test'>;
}
