// flow-typed signature: cac298a73cf37649c83e65cf5f85ad4c
// flow-typed version: <<STUB>>/purgecss-webpack-plugin_v^2.0.6/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'purgecss-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'purgecss-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'purgecss-webpack-plugin/lib/purgecss-webpack-plugin.esm' {
  declare module.exports: any;
}

declare module 'purgecss-webpack-plugin/lib/purgecss-webpack-plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'purgecss-webpack-plugin/lib/purgecss-webpack-plugin.esm.js' {
  declare module.exports: $Exports<'purgecss-webpack-plugin/lib/purgecss-webpack-plugin.esm'>;
}
declare module 'purgecss-webpack-plugin/lib/purgecss-webpack-plugin.js' {
  declare module.exports: $Exports<'purgecss-webpack-plugin/lib/purgecss-webpack-plugin'>;
}
