// flow-typed signature: 50d9ef1ea5fdc513984844e212b99952
// flow-typed version: <<STUB>>/purgecss-webpack-plugin_v^1.6.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'purgecss-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'purgecss-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'purgecss-webpack-plugin/lib/purgecss-webpack-plugin.es' {
  declare module.exports: any;
}

declare module 'purgecss-webpack-plugin/lib/purgecss-webpack-plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'purgecss-webpack-plugin/lib/purgecss-webpack-plugin.es.js' {
  declare module.exports: $Exports<'purgecss-webpack-plugin/lib/purgecss-webpack-plugin.es'>;
}
declare module 'purgecss-webpack-plugin/lib/purgecss-webpack-plugin.js' {
  declare module.exports: $Exports<'purgecss-webpack-plugin/lib/purgecss-webpack-plugin'>;
}
