// flow-typed signature: b6b6b72063d4301fa2ca8da778287e65
// flow-typed version: <<STUB>>/recaptcha-v3_v^1.7.2/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'recaptcha-v3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'recaptcha-v3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'recaptcha-v3/dist/grecaptcha/grecaptcha' {
  declare module.exports: any;
}

declare module 'recaptcha-v3/dist/ReCaptcha' {
  declare module.exports: any;
}

declare module 'recaptcha-v3/dist/ReCaptchaInstance' {
  declare module.exports: any;
}

declare module 'recaptcha-v3/dist/ReCaptchaLoader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'recaptcha-v3/dist/grecaptcha/grecaptcha.js' {
  declare module.exports: $Exports<'recaptcha-v3/dist/grecaptcha/grecaptcha'>;
}
declare module 'recaptcha-v3/dist/ReCaptcha.js' {
  declare module.exports: $Exports<'recaptcha-v3/dist/ReCaptcha'>;
}
declare module 'recaptcha-v3/dist/ReCaptchaInstance.js' {
  declare module.exports: $Exports<'recaptcha-v3/dist/ReCaptchaInstance'>;
}
declare module 'recaptcha-v3/dist/ReCaptchaLoader.js' {
  declare module.exports: $Exports<'recaptcha-v3/dist/ReCaptchaLoader'>;
}
