// flow-typed signature: 4eb02b3dd3a629ccb25c005d629dbe45
// flow-typed version: <<STUB>>/@fullhuman/postcss-purgecss_v^2.0.6/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fullhuman/postcss-purgecss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fullhuman/postcss-purgecss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fullhuman/postcss-purgecss/lib/postcss-purgecss.esm' {
  declare module.exports: any;
}

declare module '@fullhuman/postcss-purgecss/lib/postcss-purgecss' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fullhuman/postcss-purgecss/lib/postcss-purgecss.esm.js' {
  declare module.exports: $Exports<'@fullhuman/postcss-purgecss/lib/postcss-purgecss.esm'>;
}
declare module '@fullhuman/postcss-purgecss/lib/postcss-purgecss.js' {
  declare module.exports: $Exports<'@fullhuman/postcss-purgecss/lib/postcss-purgecss'>;
}
