// flow-typed signature: 70854e35b349b177c5baa5396fc96ff6
// flow-typed version: <<STUB>>/@tailwindcss/ui_v^0.3.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tailwindcss/ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tailwindcss/ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tailwindcss/ui/build' {
  declare module.exports: any;
}

declare module '@tailwindcss/ui/colors' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tailwindcss/ui/build.js' {
  declare module.exports: $Exports<'@tailwindcss/ui/build'>;
}
declare module '@tailwindcss/ui/colors.js' {
  declare module.exports: $Exports<'@tailwindcss/ui/colors'>;
}
declare module '@tailwindcss/ui/index' {
  declare module.exports: $Exports<'@tailwindcss/ui'>;
}
declare module '@tailwindcss/ui/index.js' {
  declare module.exports: $Exports<'@tailwindcss/ui'>;
}
